module.exports = {
    PAGERDUTY_API_KEY: 'xxx123',
    PAGERDUTY_INCIDENT_FROM: 'mail@sample.xx',
    PAGERDUTY_SERVICE_ID: 'XXX123',
    PAGERDUTY_PRIORITY_ID: 'XXX123',
    PAGERDUTY_ESCALATION_POLICY_ID: 'XXX123'
};
